# Not sure if we need this file or not

# Database configuration for tests
test:
  driver: postgres
  open: dbname=life_logger_test user=life_logger_app sslmode=disable

# Database configuration for local development
localhost:
  driver: postgres
  open: dbname=life_logger user=life_logger_app sslmode=disable
